### ISSUE TITLE
special characters on chapter02 code samples and utf8

### ISSUE THREAD

**Issue by alvaromlg** [ErikCH/VuejsInActionCode#1]
Hello!
I was reading through chapter 2 and noticed the ending curly quotes are different in these lines and can give some issues.

https://github.com/ErikCH/VuejsInActionCode/blob/master/chapter-02/product-markup-cont.html#L10

https://github.com/ErikCH/VuejsInActionCode/blob/master/chapter-02/v-text-binding.html#L10

Also on https://github.com/ErikCH/VuejsInActionCode/blob/master/chapter-02/index.html the meta tag `<meta charset="UTF-8">` might be needed to render special characters like `$`

These are small typos but I can submit a PR if you want.

**Comment by ErikCH** [comment]
Thanks! I pushed up a commit fixing these issues 👍
