### ISSUE TITLE
The template compiler is not available

### ISSUE THREAD

**Issue by 4e6ypaH** [ErikCH/VuejsInActionCode#5]
Hello, Erik! 
I have a problem in chapter7. I've completed all the changes, but when I run a server with "npm run serve" (I use vue-cli 3) I get a warning: 
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)

So I have no output data because of that and I have no idea how to fix it. I hope you can make it clearer for me.
![VueWarning](https://user-images.githubusercontent.com/32742552/58884985-0d974f00-86ea-11e9-9650-26756748e258.jpg)

**Comment by ErikCH** [comment]
Checked the code in the repo for chapter 7. It worked fine. I have not updated the vue version, or tried to create a new app using the new vue-cli, so I'm not sure what the problem is. Could you please share your github repo with this code so I can test!
